- integration-tests/src/test/kotlin/me/tatarka/inject/test/NestedComponentTest.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
> Fix code generation for parent provides extensions

- integration-tests/src/test/kotlin/me/tatarka/inject/test/FunctionTest.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/ProvidesTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
> More robust typename logic

- integration-tests-kapt/build.gradle
- integration-tests-kapt/src/test/kotlin/me/tatarka/inject/test/JavaxAnnotationTest.kt
- integration-tests-ksp/build.gradle
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Options.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ScopedInjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
> Support javax inject and scope annotations

- integration-tests/src/test/kotlin/me/tatarka/inject/test/TypeAliasTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
> Again, more robust type name resolution

- integration-tests/src/test/kotlin/me/tatarka/inject/test/ProvidesTest.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
> Fix param type resolution

- .circleci/config.yml
- compiler-tests/build.gradle
- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- compiler-tests/src/test/kotlin/me/tatarka/inject/test/ProjectCompiler.kt
Blocked:
- ksp: needs to be updated
- kapt: not working on 1.4.0 https://github.com/tschuchortdev/kotlin-compile-testing/issues/51
> Migrate tests to use compile testing

- integration-tests/src/test/kotlin/me/tatarka/inject/test/JavaxAnnotationTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
> support javax.inject.Qualifier

- compiler-tests/build.gradle
- compiler-tests/src/main/kotlin/me/tatarka/inject/Profile.kt
- compiler-tests/src/main/kotlin/me/tatarka/inject/ProjectCompiler.kt
- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- compiler-tests/src/test/kotlin/me/tatarka/inject/test/Utils.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Options.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Profiler.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/TypeKey.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Util.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/BaseInjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
Also removed by lazy as it wasn't really saving anything
> Speed up equals/hashcode for type collection

- compiler-tests/src/main/kotlin/me/tatarka/inject/Profile.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Options.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/BaseInjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
removes n^2 behavior and makes it easier to understand
> Update jvm signature matching

- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
> Error out if parent component is missing val

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/ComponentTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
> Fix generating incorrect code for fun providers

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/SuspendTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
> Properly handle suspend functions

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectObjectTest.kt
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/different/DifferentPackage.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
Fixes https://github.com/evant/kotlin-inject/issues/59
> Support injecting objects

- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
This fixes the most egregious issue with #110
> Compare nullable & non-nullable types as different on kapt

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InnerClassComponentTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
> Correctly handle components declared as inner classes

- README.md
- docs/testing.md
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
[Rendered](https://github.com/evant/kotlin-inject/blob/df514938de1f5230dbca3ca71784f6b0a156878b/docs/testing.md)
> Add docs on testing

- README.md
- docs/android.md
[Rendered](https://github.com/evant/kotlin-inject/blob/e01245ea973d4479c4ace71a3ffda56afaf8c47b/docs/android.md)
> Add android docs

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectObjectTest.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
> Fix generated code for @Inject on a companion object

- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
> Show a useful error message when trying to return a platform type for a @Provides

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/MultibindsTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
> Look through type alias for @IntoMap

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectFunctionTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResult.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Fix generated code for @Inject functions with a receiver

- build.gradle.kts
- gradle/libs.versions.toml
- integration-tests/ksp/build.gradle.kts
- Make multiplatform ksp dep more clear
- Add temp fix for kapt deadlock
> Update to ksp stable

- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
https://github.com/google/ksp/issues/632
> Add workaround for ksp annotation resolve issue in KMP common code

- .circleci/config.yml
- build-logic/src/main/kotlin/kotlin-inject.multiplatform.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- kotlin-inject-runtime/build.gradle.kts
- kotlin-inject-runtime/src/commonTest/kotlin/me/tatarka/inject/internal/LazyMapTest.kt
- kotlin-inject-runtime/src/jvmMain/kotlin/me/tatarka/inject/internal/LazyMap.kt
- kotlin-inject-runtime/src/jvmTest/kotlin/me/tatarka/inject/internal/LazyMapTestJvm.kt
- kotlin-inject-runtime/src/nativeMain/kotlin/me/tatarka/inject/internal/LazyMap.kt
- kotlin-inject-runtime/src/nativeTest/kotlin/me/tatarka/inject/internal/LazyMapTestNative.kt
Note: this relies on the new kotlin memory model.
Fixes #167
> Proper multithreading support on kotlin native

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/DefaultParamTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Fix default lambda or lazy params

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
> Fail if the same scope is applied both on child and parent components

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .static/detekt-config.yml
- CONTRIBUTING.md
- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/internal/Equiv.kt
- ast/kapt/src/main/kotlin/me/tatarka/kotlin/ast/KaptUtil.kt
- ast/kapt/src/main/kotlin/me/tatarka/kotlin/ast/ModelAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSUtil.kt
- build-logic/src/main/kotlin/kotlin-inject.detekt.gradle.kts
- gradle/libs.versions.toml
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Context.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/CreateGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeKey.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Util.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler/kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
- kotlin-inject-compiler/test/src/main/kotlin/me/tatarka/inject/ProjectCompiler.kt
- kotlin-inject-compiler/test/src/main/kotlin/me/tatarka/inject/SimpleClassProcessor.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
update detekt and apply some formatting fixes to mkae ktlint happy. Also committing `.idea/codeStyles` to better align idea format with ktlint.
> Detekt update

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
> Improve error message for scoped provides in unscoped component

- .circleci/config.yml
https://github.com/CircleCI-Public/browser-tools-orb/issues/62
> Fix issue with browser-tools polluting project dir breaking checkout

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Context.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultOptimizer.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> revamp the optimize step with better field naming and to be more reliable

- CHANGELOG.md
Fixed typo in date for release 0.6.0
> Fixed typo in date for release 0.6.0

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/MultibindsTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Allow multibind sets with different typealises to be treated as different types

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/RecursiveTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
> Fix compile error when accessing parent scoped dependency in cycle run block

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
> Reject assisted injection in cycles

- ast/kapt/src/main/kotlin/me/tatarka/kotlin/ast/ModelAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
> Check overridden method for provides annotation

- docs/android.md
> Update android docs with latest viewmodel functions

- gradle/libs.versions.toml
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectFunctionTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResult.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Check the correct scope when enforcing assisted injection to be unscoped

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/CycleDetector.kt
Hello @evant !
I would like to thank you for creating such a great library.
While studying your code, I found a commit that updates the kotlin version to 1.9.0. 
But new versions of Kotlin provide data objects, which can help with logging in the future.
Therefore, I carefully wrote code to refactor that code.
Thank you for checking it out!
```kotlin
// Before
sealed class CycleResult {
object None : CycleResult()
object Cycle : CycleResult()
class Resolvable(val name: String) : CycleResult()
}
```
```kotlin
// After
sealed class CycleResult {
data object None : CycleResult()
data object Cycle : CycleResult()
class Resolvable(val name: String) : CycleResult()
}
```
> Convert existing object to new feature data object

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSUtil.kt
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
> better handle duplicate member declarations in superclasses

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
> allow the same scope on component and implemented interface

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/ProvidesTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultOptimizer.kt
> fix bug where optimizer assumed references to existing provides were always properties

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/architecture.md
the README isn't touched for now and will be updated with the next release
> update docs in light of the kapt backend being removed

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
> Consider covariance when collecting type info

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSUtil.kt
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Scope.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/WarningTest.kt
> Consider Scope annotations from superclasses

- CHANGELOG.md
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/QualifierTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/QualifierComponents.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-runtime/src/commonMain/kotlin/me/tatarka/inject/annotations/Annotations.kt
note: currently only placements equivalent to javax.inject.Qualifier are supported. Allowing types to be annotated as well is planned.
Initial work for #253
> basic support for Qualifier annotations

- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
I wrote this while investigating #431 and figured it was worth still offering up in a PR if you want it!
> Add an extra test for scope annotation equality

- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/QualifierTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Models.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/QualifierComponents.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Correct qualifier for receviers

- README.md
Quick doc change on how to pass parameters.
> add doc on how to pass parameter
