- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/AbstractComponentTest.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/Models.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/NestedComponentTest.kt
- integration-tests/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/InjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ScopedInjectCompiler.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
You can define `@Provides` and `@Scope` annotations on an abstract
class/interface that components implement and pass this as a
`@Component` dependency to another component. This allows you to swap
out implementations for testing.
> Support abstract components

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/DefaultArgTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
Due to a limitation in kapt/ksp we can't read default values to declare them
ourselves. This means we need to generate create/constructor for each set of
params we want to pass. For now we only create 2, one with all the params and
one with the default params omitted.
Fixes #50
> Support default args in component constructors

- README.md
- compiler-tests/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectConstructorTest.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/Ast.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler-core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/ModelAst.kt
- kotlin-inject-compiler-kapt/src/main/kotlin/me/tatarka/inject/compiler/kapt/Util.kt
- kotlin-inject-compiler-ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/KSAst.kt
- kotlin-inject-runtime/src/main/kotlin/me/tatarka/inject/annotations/Annotations.kt
Fixes https://github.com/evant/kotlin-inject/issues/10.
> Support annotating constructors (primary and secondary) with `@Inject`

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectFunctionTest.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
This can lose annotations which may be important (ex: @Composeable)
> Fixed not using the typealias for function return types

- gradle/libs.versions.toml
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/DefaultParamTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
If a param has a default value and it's type is not found in the graph,
it will be skipped instead of throwing an error.
Fixes #161
> Allow params to be skipped if they have a default value

- gradle/libs.versions.toml
Google has released a [new build of ksp](https://github.com/google/ksp/releases/tag/1.5.31-1.0.1) with Kotlin 1.5.31 which makes it possible for projects to use kotlin-inject without needing to use an unstable version of Kotlin.
> Move back to Kotlin 1.5.31

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- If multiple scoped @Provides functions have the same return type with different type args, the generated properties will have the same name
- This causes conflicting declaration errors while compiling
- To fix that, the type args are included in property name generation
Fixes #174
> Fix conflicting declarations with scoped @Provides functions

- kotlin-inject-runtime/src/nativeMain/kotlin/me/tatarka/inject/internal/LazyMap.kt
Kotlin/native otherwise crashes when `NULL` is accessed:
```
Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread
```
I actually ran into this error when I tried my components using `IsoState` as per your suggested in https://github.com/evant/kotlin-inject/issues/167#issuecomment-970449637.
> Annotate a top-level property in LazyMap with @SharedImmutable

- build-logic/src/main/kotlin/kotlin-inject.multiplatform.gradle.kts
- kotlin-inject-runtime/src/commonMain/kotlin/me/tatarka/inject/annotations/Annotations.kt
https://youtrack.jetbrains.com/issue/KT-41082.
Fixes #181
> Remove explicit retention annotations to get rid of kotlin js warnings

- docs/android.md
- There were a few copy/paste errors where the `@Composable` was a subclass of `Fragment` rather than a function
- The modified version of the `viewModel()` function requires the template arg `VM` to be `reified`, otherwise you get the error
> Cannot use VM as a reified type parameter. Use a class instead."
- I referenced the origin of the suggested `viewModel()` helper function, as this helped me understand what it was doing
> fix a few things in the new Compose docs

- build-logic/src/main/kotlin/kotlin-inject.publish.gradle.kts
The groupId wasn't set on multiplatform artifacts
> Fix publishing

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InnerClassComponentTest.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
This makes it easier to find what class error messages are referring too
as well as fixes an incorrect cache hit when 2 inner classes in the root
package share a name.
Fixes #166, #192
> Fix printing of AstClass to print full type including outer class

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Context.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
This is a stricter version of pr #201 for #188 that is easier to
understand. This matches dagger's behavior as well (when using
subcomponents a parent component can't depend on a subcomponent's
dependency).
> Disallow depending on child deps from a parent component

- ast/kapt/build.gradle.kts
- ast/ksp/build.gradle.kts
- build-logic/src/main/kotlin/kotlin-inject.publish.gradle.kts
- integration-tests/kapt-companion/build.gradle.kts
- integration-tests/kapt/build.gradle.kts
- integration-tests/ksp-companion/build.gradle.kts
- integration-tests/ksp/build.gradle.kts
- integration-tests/module/build.gradle.kts
- kotlin-inject-compiler/core/build.gradle.kts
- kotlin-inject-compiler/kapt/build.gradle.kts
- kotlin-inject-compiler/ksp/build.gradle.kts
- kotlin-inject-compiler/test/build.gradle.kts
- settings.gradle.kts
There seemd to be an inconsistenty in pulling group/artifact id's with
the way they were done previously. Instead we are simply setting the
gradle project names to match the artifact names and set the group to
the rootProject group.
Fixes #222
> Switch to manually defining artifact names

- .circleci/config.yml
circleci recommends caches to not be more than 500mb so hopefully this
gets them closer to that size.
> Split up gradle & kotlin native caches to make them smaller

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/ArgNameAllocator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/core/src/test/kotlin/me/tatarka/inject/compiler/ArgNameAllocatorTest.kt
This is a follow up of https://github.com/evant/kotlin-inject/pull/217
Create an ArgNameAllocator and reset it between provider calls. Else, the arg names would be unique across all functions of a component.
> Make arg names not unique accross a component

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/AssistedTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Context.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
> Don't provide assisted types beyond the original level where they are declared

- docs/android.md
Hi,
I've spotted a couple of typos on the Composable annotations while using the docs so here are the fixes.
Thanks a lot for the work you put into this library it's fantastic 😍
> Fix android.md doc typos

- integration-tests/common/src/test/kotlin/me/tatarka/inject/test/InjectLambdaTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
Normally types themselves are looked up before lambda and lazy versions of that type so that if for example you are providing a lambda it resolves first to the provided type. Sets were doing it backwards which means it always treated lambdas specially instead of allowing you to provide them.
Fixes #242
> Change set multibind resolution order to match regular resolution

- .static/detekt-config.yml
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
These features don't really play well together because you'd expect the returned type to be always based on the assisted args.
Fixes #262
> Disallow scopes on types with assisted injection.

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/WarningTest.kt
It should be placed on a @Provides function or @Inject constructor instead.
Note: due to the limitation with the KAPT back-end it will miss cases where the property is annotated itself instead of it's getter. ex: `@MyScope abstract val myProp` is missed but
`@get:MyScope abstract val myProp` is caught. This can be improved once the KAPT back-end is removed.
Partially addresses #238
> Add a warning for applying a scope on a generated component function or property as it will have no effect.

- README.md
This was probably added when the project was private, but now that it is public and the token is no longer valid, we should remove it.
```bash
curl 'https://circleci.com/gh/evant/kotlin-inject.svg?style=svg&circle-token=8792fa19911be92d6a1d66dd45ece3bf6712f778'
```
`Invalid token provided.`
> Remove invalid token to fix CircleCI badge

- README.md
> fix README document bug where method was incorrectly marked protected

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
This was generating invalid code, now it gives a helpful error message.
Fixes #337
> Disallow scoped suspend provides methods

- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/QualifierTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Qualifier.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
constructor types are already resolved, since the scope type wasn't it was never matching and causing infinite recursion
Fixes #353
> resolve scope type when comparing against constructor injection

- build-logic/src/main/kotlin/NativeTargets.kt
- build-logic/src/main/kotlin/kotlin-inject.multiplatform.gradle.kts
Add support for Linux Arm64, which is a tier 2 native target: https://kotlinlang.org/docs/native-target-support.html#tier-2
> Linux Arm64

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/InheritanceTest.kt
The old mechanism depended on the order types were defined and processed them in order without respecting overridden functions. With the fix overridden functions get updated when collecting types.
Fixes #375
> Update overridden functions when collecting types

- README.md
- docs/multiplatform.md
I felt set up information was missing for multiplatform projects, I obtained these by viewing multiple samples and from kotlin-slack, so decided to add them.
Please do let me know if I missed something or if something is not correct.
> include multiplatform specific information

- CHANGELOG.md
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/ScopeTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Scope.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResult.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
ex: @NamedScope("one") and @NamedScope("two") are now treated as distinct scopes.
Fixes #377
> When comparing scope annotations, take their values into account

- .idea/codeStyles/Project.xml
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/KmpComponentCreateGenerator.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/ProcessKmpComponentCreate.kt
I missed the `Target...Accessor` part in the previous PR.
I also simplified the name, because what I had before was pretty gnarly since it was trying to avoid `FileAlreadyExistsException` in case there are multiple `@KmpComponentCreate` functions for the same `Component`.
With this new approach the following would cause a compile time error because the processor would generate two files named `KmpComponentCreateMyComponent.kt`:
```kotlin
@Component
abstract class MyComponent
@KmpComponentCreate
expect fun createKmp(): MyComponent
@KmpComponentCreate
expect fun MyComponent.Companion.createKmp(): MyComponent
```
Using the approach from before there would be no `FileAlreadyExistsException`, but the generated file names would be `KmpComponentCreateMyComponentCreateKmp.kt` and …
> Update the generated filename for KmpComponentCreate functions

- build-logic/src/main/kotlin/kotlin-inject.multiplatform.gradle.kts
- gradle/libs.versions.toml
- The version still has to be specified until the Kotlin tooling updates
> Use stable nodejs v22

- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/Util.kt
Reusing symbols between rounds is not supported and throws an error on ksp2. Unfortunately this means we need to use `getSymbolsWithAnnotation` instead of our custom functions as they are currently the only way to access updated deferred symbols. We still keep a list of the symbol names so that we can run a final processing pass on the last round.
See https://github.com/google/ksp/issues/1854
> Don't reuse symbols between rounds

- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/RecursiveTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Recursive.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
* added test for case with scoped circular lazy dependency #313
* fix for the test case by not wrapping TypeResult.Scoped with TypeResult.LateInit because wrapping is already done for TypeResult.Scoped.result if it was needed
Fixes #313
> fix generated code for scoped lazy circular dependency (#313)

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSUtil.kt
- integration-tests/common-jvm/src/test/kotlin/me/tatarka/inject/test/JavaxAnnotationTest.kt
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/QualifierTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/QualifierComponents.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
```
@Inject(@Qualifier("a") a: String)
```
and
```
@Inject(a: @Qualifier("a") String)
```
are equivalent.
For now, only annotating the outer type (no type args) is supported.
This lays the groundwork for allowing
```
typealias A = @Qualifier("a") String
```
to work in the future when typealias no longer work as a qualifier by itself.
Relates to #253
> Allows annotating types with a qualifier

- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/WarningTest.kt
Added test case for already working warning for scope annotation on property (#238) (was fixed by migration to ksp)
> add test case for scope annnotation not having effect on property (#238)

- gradle.properties
- gradle/libs.versions.toml
- integration-tests/ksp/build.gradle.kts
- kotlin-inject-runtime/build.gradle.kts
- kotlin-inject-runtime/src/nativeMain/kotlin/me/tatarka/inject/internal/LazyMap.kt
- kotlin-js-store/yarn.lock
Was investigating using KSP 2 and figured I'd start tracking this separate from that.
> Prepare for K2

- .circleci/config.yml
- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- integration-tests/common-jvm/src/test/java/me/tatarka/inject/test/JavaFoo.java
- integration-tests/common-jvm/src/test/kotlin/me/tatarka/inject/test/JavaTest.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
Allows injecting provided dependencies into java constructor even if parameter nullability is not specified in java
Fixes #401
> Consider platform nullability non-null in params

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
KSP indicates that a type can for a type argument can be null, but kotlin-inject ignored that. This caused crashes in our case:
```
java.lang.NullPointerException
at me.tatarka.kotlin.ast.KSAstType.getArguments(KSAst.kt:469)
at me.tatarka.inject.compiler.InjectGeneratorKt.qualifier$checkTypeArgs(InjectGenerator.kt:256)
at me.tatarka.inject.compiler.InjectGeneratorKt.qualifier$checkTypeArgs(InjectGenerator.kt:261)
at me.tatarka.inject.compiler.InjectGeneratorKt.qualifier$checkTypeArgs(InjectGenerator.kt:261)
at me.tatarka.inject.compiler.InjectGeneratorKt.qualifier$qualifier(InjectGenerator.kt:278)
at me.tatarka.inject.compiler.InjectGeneratorKt.qualifier(InjectGenerator.kt:283)
at me.tatarka.inject.compiler.TypeCollector.collectTypeInfo(TypeCollector.kt:391)
at …
```
> Fix `NullPointerException` when resolving types

- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/InjectProcessor.kt
Classes keep being processed multiple times and throw a `FileAlreadyExistsException` in multi round scenarios. The function `getSymbolsWithAnnotation()` returns deferred symbols twice for some reason in the next round.
The fix is only applied for classes and not functions yet, because there the issue didn't occur. More care should also be taken for functions, because the qualified name alone is not an indicator to distinguish functions as functions be overloaded and have different parameters.
> Fix `FileAlreadyExistsException`

- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
Fixes #426 
I'm not sure if this is the best solution, or why the type parameter is included in the CycleDetector. An alternate option is to catch this in the `CycleDetector` and just filter it out. Another option is to catch any exceptions from `toTypeName()` and use `typeRef.toString()` instead.
> Don't crash if the root of a trace is a TypeParameter

- .idea/codeStyles/Project.xml
- integration-tests/common-jvm/src/main/kotlin/me/tatarka/inject/test/SelfReference.kt
- integration-tests/common-jvm/src/test/kotlin/me/tatarka/inject/test/SelfReferenceTest.kt
- integration-tests/ksp/build.gradle.kts
- kotlin-inject-compiler/ksp/src/main/kotlin/me/tatarka/inject/compiler/ksp/ProcessInject.kt
These aren't used for generation so it doesn't matter if they resolve. This also fixes an issue where a companion object implementing the component interface causes a stackoverflow.
Fixes #434
> Skip validating companion & inner class types

- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/QualifierTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/QualifierComponents.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/Context.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
This ensures qualifiers are included in the comparision
Fixes #424
> Use TypeKey to track scopes

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
Minor style thing I noticed. Prior to this, constructors with no params would still always be generated when they could be omitted.
> Don't generate parameter-less constructors

- ast/core/src/main/kotlin/me/tatarka/kotlin/ast/Ast.kt
- ast/ksp/src/main/kotlin/me/tatarka/kotlin/ast/KSAst.kt
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/AssistedTest.kt
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/InjectFunctionTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Assisted.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/InjectFunction.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/InjectGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResult.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultResolver.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
- kotlin-inject-runtime/src/commonMain/kotlin/me/tatarka/inject/annotations/Annotations.kt
- Added assisted factory interface support similar to dagger
- Regular interfaces are supported alongside with functional interfaces for easier migration from dagger
- Function injection is supported with optional parameter in `@AssistedFactory` annotation instead of name matching
Closes #243
Closes #252
> Assisted factory interface

- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeCollector.kt
- kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/FailureTest.kt
> check for duplicate bindings between child and parent components

- gradle/libs.versions.toml
Upgrade KotlinPoet to `2.0.0`, which comes with fixes for line wrapping. kotlin-inject ran into these edge cases for larger components where wrong line wrapping made the code not compile. The latest version of KotlinPoet fixes these issues.
KotlinPoet depends on Kotlin `2.0.10`, therefore upgrade Kotlin and KSP at the same time.
> Upgrade KotlinPoet to the latest version

- .circleci/config.yml
- build.gradle.kts
since we have 2 releases they need to be differentiated.
> fix sonatype release

- CHANGELOG.md
- integration-tests/common-test/src/test/kotlin/me/tatarka/inject/test/NestedComponentTest.kt
- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/NestedComponent.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
> Fixed code generation when referecning a parent component provider that

- integration-tests/common/src/main/kotlin/me/tatarka/inject/test/Assisted.kt
- kotlin-inject-compiler/core/src/main/kotlin/me/tatarka/inject/compiler/TypeResultGenerator.kt
The code generation would sometimes double the `this` expressions
```kotlin
public class InjectAssistedFactoryComponent : AssistedFactoryComponent() {
override val barFactory: AssistedBarFactory
get() = object : AssistedBarFactory {
override fun build(num: Int, name: String): FactoryAssistedBar = FactoryAssistedBar(
num = num,
// compilation failure here
foo = this@InjectAssistedFactoryComponent.this@InjectAssistedFactoryComponent.provideFoo().bind,
name = name,
provided = this@InjectAssistedFactoryComponent.name
)
}
```
Continuation for [#487](https://github.com/evant/kotlin-inject/issues/487#issuecomment-2849098544)
> Fix code generation when using receiver bindings and @AssistedFactory
